<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="wittyfeed-Vostro-3558" name="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest" tests="26" failures="4" timestamp="29 Dec 2018 11:57:48 GMT" time="71.716" errors="0">
  <testcase name="CheckSearchOption" time="20.205" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckSiteLogo" time="0.021" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckHealthCategories" time="0.016" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckHumorCategories" time="15.028" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at PagesOnThePhilipino.ThePhilipinoHomePage.HumorCategories(ThePhilipinoHomePage.java:65)
at ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest.CheckHumorCategories(ThePhilipinoHomePageTestcasesTest.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckHumorCategories -->
  <testcase name="CheckTechnologyCategories" time="10.019" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at PagesOnThePhilipino.ThePhilipinoHomePage.TechnologyCategories(ThePhilipinoHomePage.java:77)
at ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest.CheckTechnologyCategories(ThePhilipinoHomePageTestcasesTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckTechnologyCategories -->
  <testcase name="CheckMiscCategories" time="10.021" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at PagesOnThePhilipino.ThePhilipinoHomePage.MiscCategories(ThePhilipinoHomePage.java:83)
at ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest.CheckMiscCategories(ThePhilipinoHomePageTestcasesTest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckMiscCategories -->
  <testcase name="CheckFactsCategories" time="10.016" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at PagesOnThePhilipino.ThePhilipinoHomePage.FactsCategories(ThePhilipinoHomePage.java:89)
at ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest.CheckFactsCategories(ThePhilipinoHomePageTestcasesTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckFactsCategories -->
  <testcase name="CheckInstaLink" time="0.012" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckTwitterLink" time="0.012" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckFacebookLink" time="0.015" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckYouTubeLink" time="0.015" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckFeaturedPostImage" time="0.012" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckFeaturedPostTitle" time="0.009" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckFeaturedPostAuthor" time="0.013" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckSecondPostImage" time="0.015" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckSecondPostTitle" time="0.013" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckSecondPostAuthor" time="0.015" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckThirdPostImage" time="0.014" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckThirdPostTitle" time="0.013" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckThirdPostAuthor" time="0.012" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckLatestStoryImage" time="1.042" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckLatestStoryTitle" time="1.045" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckLatestStoryAuthor" time="1.034" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckEatSleepReadReaptImage" time="1.031" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckEatSleepReadReaptTitle" time="1.037" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
  <testcase name="CheckEatSleepReadReaptAuthor" time="1.031" classname="ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest"/>
</testsuite> <!-- ThePhilipinoTestCases.ThePhilipinoHomePageTestcasesTest -->
